"""Constants and reference maps from pythonic names to pubg api names."""


PERSPECTIVES = ("tpp", "fpp")
GROUPS = ("solo", "duo", "squad")

gp_to_game_mode = {
    "solo": "solo",
    "duo": "duo",
    "squad": "squad",
    "solo-fpp": "solo-fpp",
    "duo-fpp": "duo-fpp",
    "squad-fpp": "squad-fpp",
}
game_mode_to_gp = {
    "solo": "solo",
    "duo": "duo",
    "squad": "squad",
    "solo-fpp": "solo-fpp",
    "duo-fpp": "duo-fpp",
    "squad-fpp": "squad-fpp",
}
gp_to_matches = {
    "solo": "matchesSolo",
    "duo": "matchesDuo",
    "squad": "matchesSquad",
    "solo-fpp": "matchesSoloFPP",
    "duo-fpp": "matchesDuoFPP",
    "squad-fpp": "matchesSquadFPP",
}
matches_to_gp = {
    "matchesSolo": "solo",
    "matchesDuo": "duo",
    "matchesSquad": "squad",
    "matchesSoloFPP": "solo-fpp",
    "matchesDuoFPP": "duo-fpp",
    "matchesSquadFPP": "squad-fpp",
}

map_to_map_name = {
    "Desert_Main": "Miramar",
    "Erangel_Main": "Erangel",
    "Savage_Main": "Sanhok",
}

map_name_to_map = {
    "Miramar": "Desert_Main",
    "Erangel": "Erangel_Main",
    "Sanhok": "Savage_Main",
}

map_dimensions = {
    "Desert_Main": [819200, 819200],
    "Erangel_Main": [819200, 819200],
    "Savage_Main": [409600, 409600],
}

true_false = {
    "false": False,
    "true": True,
}

BASE_URL = "https://api.playbattlegrounds.com"
SHARD_URL = BASE_URL + "/shards/"
STATUS_URL = BASE_URL + "/status"
TOURNAMENTS_URL = BASE_URL + "/tournaments"
PLAYER_FILTERS = {
    "player_ids": "playerIds",
    "player_names": "playerNames",
}
SHARDS = [
    "xbox-as",
    "xbox-eu",
    "xbox-na",
    "xbox-oc",
    "pc-krjp",
    "pc-jp",
    "pc-na",
    "pc-eu",
    "pc-oc",
    "pc-kakao",
    "pc-sea",
    "pc-sa",
    "pc-as",
    "pc-tournament",
]

COLORS = [
    "#fc3f3f",
    "#d93636",
    "#eb7575",
    "#eb583b",
    "#fc937e",
    "#d97e6c",
    "#eb753b",
    "#fca87e",
    "#d9916c",
    "#eb933b",
    "#ebb075",
    "#fcbd3f",
    "#d9a336",
    "#ebc475",
    "#fcdd3f",
    "#d9be36",
    "#fce77e",
    "#d9c76c",
    "#ebeb3b",
    "#fcfc7e",
    "#d9d96c",
    "#ddfc3f",
    "#bed936",
    "#d7eb75",
    "#bdfc3f",
    "#a3d936",
    "#d2fc7e",
    "#b5d96c",
    "#9efc3f",
    "#87d936",
    "#bdfc7e",
    "#a3d96c",
    "#7efc3f",
    "#6cd936",
    "#a8fc7e",
    "#91d96c",
    "#58eb3b",
    "#89eb75",
    "#3ffc3f",
    "#7efc7e",
    "#6cd96c",
    "#3beb58",
    "#7efc93",
    "#6cd97e",
    "#3ffc7e",
    "#36d96c",
    "#7efca8",
    "#6cd991",
    "#3beb93",
    "#7efcbd",
    "#6cd9a3",
    "#3ffcbd",
    "#36d9a3",
    "#75ebc4",
    "#3bebcd",
    "#7efce7",
    "#6cd9c7",
    "#3ffcfc",
    "#36d9d9",
    "#7efcfc",
    "#6cd9d9",
    "#3fddfc",
    "#36bed9",
    "#7ee7fc",
    "#6cc7d9",
    "#3fbdfc",
    "#36a3d9",
    "#7ed2fc",
    "#6cb5d9",
    "#3f9efc",
    "#3687d9",
    "#7ebdfc",
    "#6ca3d9",
    "#3f7efc",
    "#366cd9",
    "#759ceb",
    "#3b58eb",
    "#7e93fc",
    "#6c7ed9",
    "#3636d9",
    "#7e7efc",
    "#5f3ffc",
    "#937efc",
    "#7e6cd9",
    "#7e3ffc",
    "#6c36d9",
    "#9c75eb",
    "#9e3ffc",
    "#8736d9",
    "#bd7efc",
    "#a36cd9",
    "#bd3ffc",
    "#a336d9",
    "#d27efc",
    "#b56cd9",
    "#dd3ffc",
    "#be36d9",
    "#e77efc",
    "#c76cd9",
    "#fc3ffc",
    "#d936d9",
    "#fc7efc",
    "#d96cd9",
    "#eb3bcd",
    "#fc7ee7",
    "#d96cc7",
    "#fc3fbd",
    "#d936a3",
    "#fc7ed2",
    "#d96cb5",
    "#eb3b93",
    "#eb75b0",
    "#fc3f7e",
    "#d9366c",
    "#eb759c",
    "#fc3f5f",
    "#d93651",
    "#fc7e93",
    "#d96c7e",
]


item_to_item_name = {
    "Item_Ammo_12Guage_C": "12 Gauge Ammo",
    "Item_Ammo_300Magnum_C": "300 Magnum Ammo",
    "Item_Ammo_45ACP_C": ".45 ACP Ammo",
    "Item_Ammo_556mm_C": "5.56mm Ammo",
    "Item_Ammo_762mm_C": "7.62mm Ammo",
    "Item_Ammo_9mm_C": "9mm Ammo",
    "Item_Ammo_Bolt_C": "Crossbow Bolt",
    "Item_Armor_C_01_Lv3_C": "Military Vest (Level 3)",
    "Item_Armor_D_01_Lv2_C": "Police Vest (Level 2)",
    "Item_Armor_E_01_Lv1_C": "Police Vest (Level 1)",
    "Item_Attach_Weapon_Lower_AngledForeGrip_C": "Angled Foregrip",
    "Item_Attach_Weapon_Lower_Foregrip_C": "Vertical Foregrip",
    "Item_Attach_Weapon_Lower_QuickDraw_Large_Crossbow_C": "QuickDraw Crossbow Quiver",
    "Item_Attach_Weapon_Magazine_Extended_Large_C": "Large Extended Mag",
    "Item_Attach_Weapon_Magazine_Extended_Medium_C": "Medium Extended Mag",
    "Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Large_C": "Large Extended QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Medium_C": "Medium Extended QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Small_C": "Small Extended QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_ExtendedQuickDraw_SniperRifle_C": "Sniper Rifle Extended QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_Extended_Small_C": "Small Extended Mag",
    "Item_Attach_Weapon_Magazine_Extended_SniperRifle_C": "Sniper Rifle Extended Mag",
    "Item_Attach_Weapon_Magazine_QuickDraw_Large_C": "Large QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_QuickDraw_Medium_C": "Medium Quickdraw Mag",
    "Item_Attach_Weapon_Magazine_QuickDraw_Small_C": "Small Quickdraw Mag",
    "Item_Attach_Weapon_Magazine_QuickDraw_SniperRifle_C": "Sniper Rifle Quickdraw Mag",
    "Item_Attach_Weapon_Muzzle_Choke_C": "Choke",
    "Item_Attach_Weapon_Muzzle_Compensator_Large_C": "Large Compensator",
    "Item_Attach_Weapon_Muzzle_Compensator_Medium_C": "Medium Compensator",
    "Item_Attach_Weapon_Muzzle_Compensator_SniperRifle_C": "Sniper Rifle Compensator",
    "Item_Attach_Weapon_Muzzle_FlashHider_Large_C": "Large Flash Hider",
    "Item_Attach_Weapon_Muzzle_FlashHider_Medium_C": "Medium Flash Hider",
    "Item_Attach_Weapon_Muzzle_FlashHider_SniperRifle_C": "Sniper Rifle Flash Hider",
    "Item_Attach_Weapon_Muzzle_Suppressor_Large_C": "Large Supressor",
    "Item_Attach_Weapon_Muzzle_Suppressor_Medium_C": "Medium Supressor",
    "Item_Attach_Weapon_Muzzle_Suppressor_Small_C": "Small Supressor",
    "Item_Attach_Weapon_Muzzle_Suppressor_SniperRifle_C": "Sniper Rifle Supressor",
    "Item_Attach_Weapon_Stock_AR_Composite_C": "Tactical Stock",
    "Item_Attach_Weapon_Stock_Shotgun_BulletLoops_C": "Shotgun Bullet Loops",
    "Item_Attach_Weapon_Stock_SniperRifle_BulletLoops_C": "Sniper Rifle Bullet Loops",
    "Item_Attach_Weapon_Stock_SniperRifle_CheekPad_C": "Sniper Rifle Cheek Pad",
    "Item_Attach_Weapon_Stock_UZI_C": "Uzi Stock",
    "Item_Attach_Weapon_Upper_ACOG_01_C": "4x ACOG Scope",
    "Item_Attach_Weapon_Upper_Aimpoint_C": "2x Aimpoint Scope",
    "Item_Attach_Weapon_Upper_CQBSS_C": "8x CQBSS Scope",
    "Item_Attach_Weapon_Upper_DotSight_01_C": "Red Dot Sight",
    "Item_Attach_Weapon_Upper_Holosight_C": "Holographic Sight",
    "Item_Attach_Weapon_Upper_PM2_01_C": "15x PM II Scope",
    "Item_Back_B_01_StartParachutePack_C": "Parachute",
    "Item_Back_C_01_Lv3_C": "Backpack (Level 3)",
    "Item_Back_C_02_Lv3_C": "Backpack (Level 3)",
    "Item_Back_E_01_Lv1_C": "Backpack (Level 1)",
    "Item_Back_E_02_Lv1_C": "Backpack (Level 1)",
    "Item_Back_F_01_Lv2_C": "Backpack (Level 2)",
    "Item_Back_F_02_Lv2_C": "Backpack (Level 2)",
    "Item_Boost_AdrenalineSyringe_C": "Adrenaline Syringe",
    "Item_Boost_EnergyDrink_C": "Energy Drink",
    "Item_Boost_PainKiller_C": "Painkiller",
    "Item_Ghillie_01_C": "Ghillie Suit",
    "Item_Ghillie_02_C": "Ghillie Suit",
    "Item_Head_E_01_Lv1_C": "Motorcycle Helmet (Level 1)",
    "Item_Head_E_02_Lv1_C": "Motorcycle Helmet (Level 1)",
    "Item_Head_F_01_Lv2_C": "Military Helmet (Level 2)",
    "Item_Head_F_02_Lv2_C": "Military Helmet (Level 2)",
    "Item_Head_G_01_Lv3_C": "Spetsnaz Helmet (Level 3)",
    "Item_Heal_Bandage_C": "Bandage",
    "Item_Heal_FirstAid_C": "First Aid Kit",
    "Item_Heal_MedKit_C": "Med kit",
    "Item_JerryCan_C": "Gas Can",
    "Item_Weapon_AK47_C": "AKM",
    "Item_Weapon_AUG_C": "AUG A3",
    "Item_Weapon_AWM_C": "AWM",
    "Item_Weapon_Berreta686_C": "S686",
    "Item_Weapon_Cowbar_C": "Crowbar",
    "Item_Weapon_Crossbow_C": "Crossbow",
    "Item_Weapon_DP28_C": "DP-28",
    "Item_Weapon_FlashBang_C": "Flashbang",
    "Item_Weapon_G18_C": "P18C",
    "Item_Weapon_Grenade_C": "Frag Grenade",
    "Item_Weapon_Groza_C": "Groza",
    "Item_Weapon_HK416_C": "M416",
    "Item_Weapon_Kar98k_C": "Kar98k",
    "Item_Weapon_M16A4_C": "M16A4",
    "Item_Weapon_M1911_C": "P1911",
    "Item_Weapon_M249_C": "M249",
    "Item_Weapon_M24_C": "M24",
    "Item_Weapon_M9_C": "P92",
    "Item_Weapon_Machete_C": "Machete",
    "Item_Weapon_Mini14_C": "Mini 14",
    "Item_Weapon_Mk14_C": "Mk14 EBR",
    "Item_Weapon_Molotov_C": "Molotov Cocktail",
    "Item_Weapon_NagantM1895_C": "R1895",
    "Item_Weapon_Pan_C": "Pan",
    "Item_Weapon_Rhino_C": "R45",
    "Item_Weapon_Saiga12_C": "S12K",
    "Item_Weapon_Sawnoff_C": "Sawed-off",
    "Item_Weapon_SCAR-L_C": "SCAR-L",
    "Item_Weapon_Sickle_C": "Sickle",
    "Item_Weapon_SKS_C": "SKS",
    "Item_Weapon_SmokeBomb_C": "Smoke Genade",
    "Item_Weapon_Thompson_C": "Tommy Gun",
    "Item_Weapon_UMP_C": "UMP9",
    "Item_Weapon_UZI_C": "Micro Uzi",
    "Item_Weapon_Vector_C": "Vector",
    "Item_Weapon_VSS_C": "VSS",
    "Item_Weapon_Win1894_C": "Win94",
    "Item_Weapon_Winchester_C": "S1897",
    "Item_Weapon_FNFal_C": "SLR"
}


vehicle_to_vehicle_name = {
    "AquaRail_A_01_C": "Aquarail",
    "Boat_PG117_C": "PG-117",
    "BP_Motorbike_04_C": "Motorcycle",
    "BP_Motorbike_04_Desert_C": "Motorcycle",
    "BP_Motorbike_04_SideCar_C": "Motorcycle (Sidecar)",
    "BP_Motorbike_04_SideCar_Desert_C": "Motorcycle (Sidecar)",
    "BP_PickupTruck_A_01_C": "Pickup Truck",
    "BP_PickupTruck_A_02_C": "Pickup Truck",
    "BP_PickupTruck_A_03_C": "Pickup Truck",
    "BP_PickupTruck_A_04_C": "Pickup Truck",
    "BP_PickupTruck_A_05_C": "Pickup Truck",
    "BP_PickupTruck_B_01_C": "Pickup Truck",
    "BP_PickupTruck_B_02_C": "Pickup Truck",
    "BP_PickupTruck_B_03_C": "Pickup Truck",
    "BP_PickupTruck_B_04_C": "Pickup Truck",
    "BP_PickupTruck_B_05_C": "Pickup Truck",
    "BP_Van_A_01_C": "Van",
    "BP_Van_A_02_C": "Van",
    "BP_Van_A_03_C": "Van",
    "Buggy_A_01_C": "Buggy",
    "Buggy_A_02_C": "Buggy",
    "Buggy_A_03_C": "Buggy",
    "Buggy_A_04_C": "Buggy",
    "Buggy_A_05_C": "Buggy",
    "Buggy_A_06_C": "Buggy",
    "Dacia_A_01_v2_C": "Dacia 1300",
    "Dacia_A_02_v2_C": "Dacia 1300",
    "Dacia_A_03_v2_C": "Dacia 1300",
    "Dacia_A_04_v2_C": "Dacia 1300",
    "DummyTransportAircraft_C": "C-130",
    "ParachutePlayer_C": "Parachute",
    "PG117_A_01_C": "PG-117",
    "Uaz_A_01_C": "UAZ",
    "Uaz_B_01_C": "UAZ",
    "Uaz_C_01_C": "UAZ",
}


damage_causer_to_name = {
    "BattleRoyaleModeController_Def_C": "Bluezone",
    "BattleRoyaleModeController_Desert_C": "Bluezone",
    "Boat_PG117_C": "PG-117",
    "BP_Motorbike_04_C": "Motorcycle",
    "BP_Motorbike_04_Desert_C": "Motorcycle",
    "BP_Motorbike_04_SideCar_C": "Motorcycle (Sidecar)",
    "BP_Motorbike_04_SideCar_Desert_C": "Motorcycle (Sidecar)",
    "BP_PickupTruck_A_01_C": "Pickup Truck",
    "BP_PickupTruck_A_02_C": "Pickup Truck",
    "BP_PickupTruck_A_03_C": "Pickup Truck",
    "BP_PickupTruck_A_04_C": "Pickup Truck",
    "BP_PickupTruck_A_05_C": "Pickup Truck",
    "BP_PickupTruck_B_01_C": "Pickup Truck",
    "BP_PickupTruck_B_02_C": "Pickup Truck",
    "BP_PickupTruck_B_03_C": "Pickup Truck",
    "BP_PickupTruck_B_04_C": "Pickup Truck",
    "BP_PickupTruck_B_05_C": "Pickup Truck",
    "BP_Van_A_01_C": "Van",
    "BP_Van_A_02_C": "Van",
    "BP_Van_A_03_C": "Van",
    "Buff_DecreaseBreathInApnea_C": "Drowning",
    "Buff_FireDOT_C": "Burning",
    "Buggy_A_01_C": "Buggy",
    "Buggy_A_02_C": "Buggy",
    "Buggy_A_03_C": "Buggy",
    "Buggy_A_04_C": "Buggy",
    "Buggy_A_05_C": "Buggy",
    "Buggy_A_06_C": "Buggy",
    "Dacia_A_01_v2_C": "Dacia",
    "Dacia_A_02_v2_C": "Dacia",
    "Dacia_A_03_v2_C": "Dacia",
    "Dacia_A_04_v2_C": "Dacia",
    "PlayerFemale_A_C": "Player",
    "PlayerMale_A_C": "Player",
    "ProjGrenade_C": "Grenade",
    "ProjMolotov_C": "Molotov Cocktail",
    "ProjMolotov_DamageField_C": "Molotov Cocktail",
    "ProjMolotov_DamageFieldInWall_C": "Molotov Cocktail",
    "RedZoneBomb_C": "Redzone",
    "Uaz_A_01_C": "UAZ",
    "Uaz_B_01_C": "UAZ",
    "Uaz_C_01_C": "UAZ",
    "WeapAK47_C": "AKM",
    "WeapAUG_C": "AUG A3",
    "WeapAWM_C": "AWM",
    "WeapBerreta686_C": "S686",
    "WeapCowbar_C": "Crowbar",
    "WeapCrossbow_1_C": "Crossbow",
    "WeapDP28_C": "DP-28",
    "WeapG18_C": "P18C",
    "WeapGroza_C": "Groza",
    "WeapHK416_C": "M416",
    "WeapKar98k_C": "Kar98k",
    "WeapM16A4_C": "M16A4",
    "WeapM1911_C": "P1911",
    "WeapM249_C": "M249",
    "WeapM24_C": "M24",
    "WeapM9_C": "P92",
    "WeapMachete_C": "Machete",
    "WeapMini14_C": "Mini 14",
    "WeapMk14_C": "Mk14 EBR",
    "WeapNagantM1895_C": "R1895",
    "WeapPan_C": "Pan",
    "WeapRhino_C": "R45",
    "WeapSaiga12_C": "S12K",
    "WeapSawnoff_C": "Sawed-off",
    "WeapSCAR-L_C": "SCAR-L",
    "WeapSickle_C": "Sickle",
    "WeapSKS_C": "SKS",
    "WeapThompson_C": "Tommy Gun",
    "WeapUMP_C": "UMP9",
    "WeapUZI_C": "Micro Uzi",
    "WeapVector_C": "Vector",
    "WeapVSS_C": "VSS",
    "WeapWin94_C": "Win94",
    "WeapWinchester_C": "S1897",
    "WeapFNFal_C": "SLR",
}


damage_type_to_name = {
    "Damage_BlueZone": "Bluezone",
    "Damage_Drown": "Drowning",
    "Damage_Explosion_Grenade": "Grenade Explosion",
    "Damage_Explosion_RedZone": "Redzone Explosion",
    "Damage_Explosion_Vehicle": "Vehicle Explosion",
    "Damage_Groggy": "Bleed Out",
    "Damage_Gun": "Gun",
    "Damage_Instant_Fall": "Fall",
    "Damage_Melee": "Melee",
    "Damage_Molotov": "Molotov",
    "Damage_VehicleCrashHit": "Vehicle Crash",
    "Damage_VehicleHit": "Vehicle",
}
